name:                learn-haskell
version:             0.1.0.0
github:              "retriku/learn-haskell"
license:             BSD3
author:              "Renars Kudins"
maintainer:          "renars.kudins@gmail.com"
copyright:           "2019 Renars Kudins"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/retriku/learn-haskell#readme>

dependencies:
- base >= 4.7 && < 5
- mtl
- text
- acme-missiles
- random
- containers
- transformers

library:
  source-dirs:
    - src
    - src/katas

executables:
  learn-haskell-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - learn-haskell

tests:
  learn-haskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - learn-haskell
    - hspec
    - QuickCheck
